### ISSUE TITLE
Feature Request: Update to sdk to 5.1.2+

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#156]
Update native sdks to newer version, mainly for 3d extrusions.

https://blog.mapbox.com/3d-map-visualizations-on-android-and-ios-81461cd384f8
https://www.mapbox.com/android-docs/api/map-sdk/5.1.2/index.html

Android examples:
https://github.com/mapbox/mapbox-android-demo/tree/5937a1c4cb677f2056deb9170792e169a85b4fa0/MapboxAndroidDemo/src/main/java/com/mapbox/mapboxandroiddemo/examples/extrusions

**Comment by EddyVerbruggen** [comment]
Hey Brad,

I've just pushed an SDK update to GitHub:
- Android 5.1.2
- iOS 3.6

Both of those support what you request but there's nothing exposed by the plugin API yet. I'll keep this issue open for that reason.

Btw Mapbox also included two new styles that are really cool, so I've exposed those already: `TRAFFIC_DAY` and `TRAFFIC_NIGHT`, see this Tweet for how those look: https://twitter.com/eddyverbruggen/status/898222320707305477

**Comment by bradmartin** [comment]
Awesome stuff 👍 - if I get time and have to do the 3d textures for a client I'll get a PR in here but client is still in the air right now 😄 so we shall see.

**Comment by EddyVerbruggen** [comment]
Cool, well, please open a new issue if you need to - I've just published 3.1.0 which also allows you to access the native MapView classes from `mapReady` and `show` which may come in handy if you want to play with those layers in your app's code instead of the plugin code. See the readme and demo for how to grab those native objects. Their types are listed in the typings of `ShowResult`:

https://github.com/EddyVerbruggen/nativescript-mapbox/blob/b46794f9fb293e0986c6c988b63938279a8772c0/src/mapbox.common.ts#L236-L239
