### ISSUE TITLE
Set location manually for demo simulation - Question 

### ISSUE THREAD

**Issue by d3mac123** [Yermo/nativescript-mapbox#192]
Is there a way to set location without using location services? I would like to simulate a trip between several points (having the map moving and the location icon positioned in the “fake” coordinates) to showcase some features of my app.

**Comment by EddyVerbruggen** [comment]
On iOS the `userLocation` is a readonly field. On Android I think it would be possible because the location plugin I'm using has [this code](https://github.com/mapbox/mapbox-plugins-android/blob/bea4e19fcdf44934fd9e1c5bfbbb0dc67a059113/plugin-locationlayer/src/main/java/com/mapbox/mapboxsdk/plugins/locationlayer/LocationLayerPlugin.java#L537-L559). However, I'm not going to add a non-x-platform function to the plugin.

Can't you use a marker that closely resembles a user location and move that around?
