### ISSUE TITLE
Failed to bind EAGLDrawable

### ISSUE THREAD

**Issue by bigdaddio** [Yermo/nativescript-mapbox#196]
I get this error and of course no map.
Page1 I create and draw a map via XML.
(destroy map and go to Page2)
Page 2 something else 
page 3 something else
Page4 try to create another map XML and get the error.
This is how I create the map on both pages. However the first page I have the map fullscreen.
I also found this error on mapbox-gl-native project and wonder if they could be related?
```
<StackLayout width="100%" height="60%" backgroundColor="blue" >
            <map:MapboxView
                delay="0"
                latitude="0"
                longitude="0"
                zoomLevel="13"
                disableZoom="false"
                disableRotation="true"
                disableScroll="false"
                disableTilt="true"
                showUserLocation="true"
                hideAttribution="true"
                mapStyle="emerald"
                hideLogo="true"
                accessToken="***"
                mapReady="onMapReady">
            </map:MapboxView>
</StackLayout>
```

**Comment by EddyVerbruggen** [comment]
Can you link to that issue?

**Comment by bigdaddio** [comment]
Of course:
https://github.com/mapbox/mapbox-gl-native/issues/1243
https://github.com/mapbox/mapbox-gl-native/issues/1572

**Comment by EddyVerbruggen** [comment]
Thank you.

I have not seen this issue myself, but changing the embedded demo app from a GridLayout to your StackLayout doesn't render a map (without an error). So I started digging.

Turns out the height property of the StackLayout isn't propagated down to the MapboxView automatically (the width is) so the height is 0 and the map is invisible.

I've changed the plugin code to apply the parent width/height if you didn't explicitly set those properties on the MapboxView object, and now the map will automatically fill the available space in the parent container.
