### ISSUE TITLE
Error while initializing Mapbox 

### ISSUE THREAD

**Issue by anaszgh** [Yermo/nativescript-mapbox#227]
Hello,

I'm using plugin version 3.3.0 with TNS version 3.4.1
i have went through the steps, when the view renders and i can see the Map on the screen (still black and trying to load) an exception is throws
```
An uncaught Exception occurred on "main" thread.
com.tns.NativeScriptException: 
Calling js method run failed

Error: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6494)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/lib/x86, /data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
    dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
    java.lang.ClassLoader.loadClass(ClassLoader.java:379)
    java.lang.ClassLoader.loadClass(ClassLoader.java:312)
    com.tns.Runtime.callJSMethodNative(Native Method)
    com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
    com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
    com.tns.Runtime.callJSMethod(Runtime.java:957)
    com.tns.Runtime.callJSMethod(Runtime.java:941)
    com.tns.Runtime.callJSMethod(Runtime.java:933)
    com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
    android.os.Handler.handleCallback(Handler.java:790)
    android.os.Handler.dispatchMessage(Handler.java:99)
    android.os.Looper.loop(Looper.java:164)
    android.app.ActivityThread.main(ActivityThread.java:6494)
    java.lang.reflect.Method.invoke(Native Method)
    com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
File: "file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js, line: 142, column: 24

StackTrace: 
	Frame: function:'_showLocation', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 145, column: 31
	Frame: function:'', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-mapbox/mapbox.js', line: 51, column: 37
	Frame: function:'ZoneDelegate.invokeTask', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 398, column: 31
	Frame: function:'Zone.runTask', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 165, column: 47
	Frame: function:'ZoneTask.invoke', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 460, column: 38
	Frame: function:'timer', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 1636, column: 29
	Frame: function:'invoke', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 19, column: 48
	Frame: function:'ZoneDelegate.invoke', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 365, column: 26
	Frame: function:'Zone.runGuarded', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 138, column: 47
	Frame: function:'', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/nativescript-angular/zone-js/dist/zone-nativescript.js', line: 116, column: 29
	Frame: function:'run', file:'file:///data/data/com.eventrest.mobile/files/app/tns_modules/tns-core-modules/timer/timer.js', line: 23, column: 13


	at com.tns.Runtime.callJSMethodNative(Native Method)
	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1088)
	at com.tns.Runtime.callJSMethodImpl(Runtime.java:970)
	at com.tns.Runtime.callJSMethod(Runtime.java:957)
	at com.tns.Runtime.callJSMethod(Runtime.java:941)
	at com.tns.Runtime.callJSMethod(Runtime.java:933)
	at com.tns.gen.java.lang.Runnable.run(Runnable.java:10)
	at android.os.Handler.handleCallback(Handler.java:790)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loop(Looper.java:164)
	at android.app.ActivityThread.main(ActivityThread.java:6494)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/arch/lifecycle/LifecycleObserver;
	... 14 more
Caused by: java.lang.ClassNotFoundException: Didn't find class "android.arch.lifecycle.LifecycleObserver" on path: DexPathList[[zip file "/data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/base.apk"],nativeLibraryDirectories=[/data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/lib/x86, /data/app/com.eventrest.mobile-W5wL4B1xCpHMoH0uRyjn6Q==/base.apk!/lib/x86, /system/lib, /vendor/lib]]
	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:125)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
	... 14 more

```

**Comment by EddyVerbruggen** [comment]
Does the demo app work for you?

**Comment by thukuwanjiku** [comment]
@EddyVerbruggen I'm having a similar error when I run the Map with showUserLocation=true. When I set it to false, it compiles successfully. 

```
<template>
    <Page>
        <ActionBar title="Mapbox"/>


        <GridLayout columns="*" rows="*">
            <StackLayout col="0" row="0">

                <Mapbox
                        accessToken="MY ACCESS TOKEN"
                        mapStyle="traffic_day"
                        :latitude="-1.28333"
                        :longitude="36.81667"
                        :hideCompass="true"
                        :zoomLevel="12"
                        :showUserLocation="true"
                        :disableZoom="false"
                        :disableRotation="false"
                        :disableScroll="false"
                        :disableTilt="false"
                        @mapReady="mapReady"
                        >
                </Mapbox>

            </StackLayout>

        </GridLayout>

    </Page>
</template>

<script>

    export default {
        data() {
            return {
                mapbox: null,
            }
        },

        created(){
            setTimeout(()=>{
                this.mapboxRoute();
            }, 
        },

        methods:{
            mapReady(args) {
                this.mapbox = args.object

                this.mapbox.hasFineLocationPermission().then(
                    function(granted) {
                        if(!granted){
                            this.mapbox.requestFineLocationPermission()
                                .then(() =>{
                                    console.log("Requested Permission");
                                });
                        }
                        // if this is 'false' you probably want to call 'requestFineLocationPermission' now
                        console.log("Has Location Permission? " + granted);
                    });
            },

            mapboxRoute(){
                this.mapbox.addPolyline({
                    id: 1, // optional, can be used in 'removePolylines'
                    color: '#336699', // Set the color of the line (default black)
                    width: 7, // Set the width of the line (default 5)
                    opacity: 0.6, //Transparency / alpha, ranging 0-1. Default fully opaque (1).
                    points: [
                        {
                            'lat': -1.28333, // mandatory
                            'lng': 36.81667 // mandatory
                        },
                        {
                            'lat': -1.30333,
                            'lng': 36.82667
                        },
                        {
                            'lat': -1.32333,
                            'lng': 36.85667
                        }
                    ]
                });
            }
        }
    }
</script>
```

Error Log

System.err: Error: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
System.err:     com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:400)
System.err:     java.lang.Class.forName(Class.java:326)
System.err:     com.mapbox.android.core.location.ClasspathChecker.hasDependencyOnClasspath(ClasspathChecker.java:8)
System.err:     com.mapbox.android.core.location.GoogleLocationEngineFactory.hasDependencyOnClasspath(GoogleLocationEngineFactory.java:22)
System.err:     com.mapbox.android.core.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:53)
System.err:     com.mapbox.android.core.location.LocationEngineProvider.<init>(LocationEngineProvider.java:22)
System.err:     com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initializeLocationEngine(LocationLayerPlugin.java:795)
System.err:     com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:137)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err:     android.os.Handler.handleCallback(Handler.java:836)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:203)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6259)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.thukuwanjiku.nami-1/base.apk"],nativeLibraryDirectories=[/data/app/com.thukuwanjiku.nami-1/lib/arm, /data/app/com.thukuwanjiku.nami-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
System.err:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err:     com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
System.err:     java.lang.Class.classForName(Native Method)
System.err:     java.lang.Class.forName(Class.java:400)
System.err:     java.lang.Class.forName(Class.java:326)
System.err:     com.mapbox.android.core.location.ClasspathChecker.hasDependencyOnClasspath(ClasspathChecker.java:8)
System.err:     com.mapbox.android.core.location.GoogleLocationEngineFactory.hasDependencyOnClasspath(GoogleLocationEngineFactory.java:22)
System.err:     com.mapbox.android.core.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:53)
System.err:     com.mapbox.android.core.location.LocationEngineProvider.<init>(LocationEngineProvider.java:22)
System.err:     com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initializeLocationEngine(LocationLayerPlugin.java:795)
System.err:     com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:137)
System.err:     com.tns.Runtime.callJSMethodNative(Native Method)
System.err:     com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err:     com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err:     com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err:     com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err:     android.os.Handler.handleCallback(Handler.java:836)
System.err:     android.os.Handler.dispatchMessage(Handler.java:103)
System.err:     android.os.Looper.loop(Looper.java:203)
System.err:     android.app.ActivityThread.main(ActivityThread.java:6259)
System.err:     java.lang.reflect.Method.invoke(Native Method)
System.err:     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
System.err:     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
System.err: File: "file:///data/data/com.thukuwanjiku.nami/files/app/vendor.js, line: 26368, column: 25
System.err: 
System.err: StackTrace: 
System.err: 	Frame: function:'_showLocation', file:'file:///data/data/com.thukuwanjiku.nami/files/app/vendor.js', line: 26368, column: 26
System.err: 	Frame: function:'', file:'file:///data/data/com.thukuwanjiku.nami/files/app/vendor.js', line: 26245, column: 19
System.err: 	Frame: function:'invoke', file:'file:///data/data/com.thukuwanjiku.nami/files/app/vendor.js', line: 53654, column: 21
System.err: 	Frame: function:'run', file:'file:///data/data/com.thukuwanjiku.nami/files/app/vendor.js', line: 53660, column: 7
System.err: 
System.err: 	at com.tns.Runtime.callJSMethodNative(Native Method)
System.err: 	at com.tns.Runtime.dispatchCallJSMethodNative(Runtime.java:1116)
System.err: 	at com.tns.Runtime.callJSMethodImpl(Runtime.java:996)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:983)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:967)
System.err: 	at com.tns.Runtime.callJSMethod(Runtime.java:959)
System.err: 	at com.tns.gen.java.lang.Runnable.run(Runnable.java:15)
System.err: 	at android.os.Handler.handleCallback(Handler.java:836)
System.err: 	at android.os.Handler.dispatchMessage(Handler.java:103)
System.err: 	at android.os.Looper.loop(Looper.java:203)
System.err: 	at android.app.ActivityThread.main(ActivityThread.java:6259)
System.err: 	at java.lang.reflect.Method.invoke(Native Method)
System.err: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
System.err: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/api/Api$zzf;
System.err: 	at com.google.android.gms.location.LocationServices.<clinit>(Unknown Source)
System.err: 	at java.lang.Class.classForName(Native Method)
System.err: 	at java.lang.Class.forName(Class.java:400)
System.err: 	at java.lang.Class.forName(Class.java:326)
System.err: 	at com.mapbox.android.core.location.ClasspathChecker.hasDependencyOnClasspath(ClasspathChecker.java:8)
System.err: 	at com.mapbox.android.core.location.GoogleLocationEngineFactory.hasDependencyOnClasspath(GoogleLocationEngineFactory.java:22)
System.err: 	at com.mapbox.android.core.location.LocationEngineProvider.initAvailableLocationEngines(LocationEngineProvider.java:53)
System.err: 	at com.mapbox.android.core.location.LocationEngineProvider.<init>(LocationEngineProvider.java:22)
System.err: 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.initializeLocationEngine(LocationLayerPlugin.java:795)
System.err: 	at com.mapbox.mapboxsdk.plugins.locationlayer.LocationLayerPlugin.<init>(LocationLayerPlugin.java:137)
System.err: 	... 14 more
System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.common.api.Api$zzf" on path: DexPathList[[zip file "/data/app/com.thukuwanjiku.nami-1/base.apk"],nativeLibraryDirectories=[/data/app/com.thukuwanjiku.nami-1/lib/arm, /data/app/com.thukuwanjiku.nami-1/base.apk!/lib/armeabi-v7a, /system/lib, /vendor/lib, /system/vendor/lib]]
System.err: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
System.err: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
System.err: 	... 24 more
^CExecuting after-watch hook from /home/thuku/Documents/Projects/vuejs/nsvNami/hooks/after-watch/nativescript-dev-webpack.js
Stopping webpack watch
Executing after-watch hook from /home/thuku/Documents/Projects/vuejs/nsvNami/hooks/after-watch/nativescript-dev-webpack.js
Stopping webpack watch

**Comment by n4lexeev** [comment]
same error as @thukuwanjiku
