### ISSUE TITLE
Enhancement: expose other methods to XML map

### ISSUE THREAD

**Issue by bradmartin** [Yermo/nativescript-mapbox#44]
Several much needed methods on the XML declared maps:
- `removeMarkers`
- `setCenter`
- `setZoomLevel`
- `addPolyline`

All of them would be great of course but these would seem to cover a lot of use cases for having dynamic capabilites of the map once its rendered for navigational purposes.

**Comment by giovannicandido** [comment]
I'm trying to come up with the use case:

If I use the programatic API I have full control, but the map overlap's everything. I need the map to stay in the GridLayout, so I can use floating action buttons and navigation drawer.

The only way to do that, at least as I could come with, is to use the XML Map.

But XML need to have the full API in order to be useful in my case.

**Comment by EddyVerbruggen** [comment]
Yes @giovannicandido that's indeed what this issue is for.

**Comment by EddyVerbruggen** [comment]
Now available are: `setViewport`, `addMarkers`, `removeMarkers`, `setCenter`, `setZoomLevel`, `setViewport`, `setTilt`, `animateCamera`, `addPolygon` and `addPolyline`.

Note that as before `addPolygon` and `addPolyline` don't work yet on iOS but those are still on my radar.

Part of 2.1.1 which I'll publish soon.

**Comment by bradmartin** [comment]
Works GREAT. Thanks @EddyVerbruggen

**Comment by EddyVerbruggen** [comment]
Cool, thanks for the quick test! :)
